# This is a basic workflow to help you get started with Actions

name: caller

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/actions/workflows/callee/dispatches \
            --header 'accept: application/vnd.github+json' \ 
            --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            --data '{"ref":"main","inputs":{}}'
          echo ${{ github.repository }}
          echo ${{ secrets.GITHUB_TOKEN }}
